version: '3.8'

services:
  my_mongo_db:
    image: mongo:6.0
    ports:
     - 27017:27017
    volumes:
     - ./bd/mongodb:/data/db

  mysql:
    image: mysql:8.0.33
    environment:
     - MYSQL_ROOT_PASSWORD=1234
    ports:
     - 3309:3306
    volumes:
     - ./bd/mysql:/var/lib/mysql

  mymariadb:
    image: mariadb:10.6.14
    environment:
      - MARIADB_ROOT_PASSWORD=4321
    ports:
     - 3307:3306
    volumes:
     - ./bd/mariadb:/var/lib/mysql

  my_express:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:5000

    environment:
      - MONGO_DB_HOST=my_mongo_db

      - MARIADB_HOST=mymariadb
      - MARIADB_USER=root
      - MARIADB_PASSWORD=4321 

      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    volumes:
      - ./server:/servidor
      - /servidor/node_modules

  